import React from 'react';
export const aiDetails = () => <div>ai distinct</div>;
export const ai_detail_0 = (p:any)=> <div>ai 0 formation</div>;
export const ai_detail_1 = (p:any)=> <div>ai 1 attack</div>;
export const ai_detail_2 = (p:any)=> <div>ai 2 patrol</div>;
export const ai_detail_3 = (p:any)=> <div>ai 3 state machine</div>;
export const ai_detail_4 = (p:any)=> <div>ai 4 formation</div>;
export const ai_detail_5 = (p:any)=> <div>ai 5 attack</div>;
export const ai_detail_6 = (p:any)=> <div>ai 6 patrol</div>;
export const ai_detail_7 = (p:any)=> <div>ai 7 state machine</div>;
export const ai_detail_8 = (p:any)=> <div>ai 8 formation</div>;
export const ai_detail_9 = (p:any)=> <div>ai 9 attack</div>;
export const ai_detail_10 = (p:any)=> <div>ai 10 patrol</div>;
export const ai_detail_11 = (p:any)=> <div>ai 11 state machine</div>;
export const ai_detail_12 = (p:any)=> <div>ai 12 formation</div>;
export const ai_detail_13 = (p:any)=> <div>ai 13 attack</div>;
export const ai_detail_14 = (p:any)=> <div>ai 14 patrol</div>;
export const ai_detail_15 = (p:any)=> <div>ai 15 state machine</div>;
export const ai_detail_16 = (p:any)=> <div>ai 16 formation</div>;
export const ai_detail_17 = (p:any)=> <div>ai 17 attack</div>;
export const ai_detail_18 = (p:any)=> <div>ai 18 patrol</div>;
export const ai_detail_19 = (p:any)=> <div>ai 19 state machine</div>;