import React from 'react';
export const analyticsDetails = () => <div>analytics distinct</div>;
export const analytics_detail_0 = (p:any)=> <div>analytics 0 APM</div>;
export const analytics_detail_1 = (p:any)=> <div>analytics 1 match stats</div>;
export const analytics_detail_2 = (p:any)=> <div>analytics 2 replay</div>;
export const analytics_detail_3 = (p:any)=> <div>analytics 3 heatmap</div>;
export const analytics_detail_4 = (p:any)=> <div>analytics 4 APM</div>;
export const analytics_detail_5 = (p:any)=> <div>analytics 5 match stats</div>;
export const analytics_detail_6 = (p:any)=> <div>analytics 6 replay</div>;
export const analytics_detail_7 = (p:any)=> <div>analytics 7 heatmap</div>;
export const analytics_detail_8 = (p:any)=> <div>analytics 8 APM</div>;
export const analytics_detail_9 = (p:any)=> <div>analytics 9 match stats</div>;
export const analytics_detail_10 = (p:any)=> <div>analytics 10 replay</div>;
export const analytics_detail_11 = (p:any)=> <div>analytics 11 heatmap</div>;
export const analytics_detail_12 = (p:any)=> <div>analytics 12 APM</div>;
export const analytics_detail_13 = (p:any)=> <div>analytics 13 match stats</div>;
export const analytics_detail_14 = (p:any)=> <div>analytics 14 replay</div>;
export const analytics_detail_15 = (p:any)=> <div>analytics 15 heatmap</div>;
export const analytics_detail_16 = (p:any)=> <div>analytics 16 APM</div>;
export const analytics_detail_17 = (p:any)=> <div>analytics 17 match stats</div>;
export const analytics_detail_18 = (p:any)=> <div>analytics 18 replay</div>;
export const analytics_detail_19 = (p:any)=> <div>analytics 19 heatmap</div>;