import React from 'react';
export const simulationDetails = () => <div>simulation distinct</div>;
export const simulation_detail_0 = (p:any)=> <div>simulation 0 lockstep</div>;
export const simulation_detail_1 = (p:any)=> <div>simulation 1 fixed point</div>;
export const simulation_detail_2 = (p:any)=> <div>simulation 2 tick 16ms</div>;
export const simulation_detail_3 = (p:any)=> <div>simulation 3 determinism</div>;
export const simulation_detail_4 = (p:any)=> <div>simulation 4 lockstep</div>;
export const simulation_detail_5 = (p:any)=> <div>simulation 5 fixed point</div>;
export const simulation_detail_6 = (p:any)=> <div>simulation 6 tick 16ms</div>;
export const simulation_detail_7 = (p:any)=> <div>simulation 7 determinism</div>;
export const simulation_detail_8 = (p:any)=> <div>simulation 8 lockstep</div>;
export const simulation_detail_9 = (p:any)=> <div>simulation 9 fixed point</div>;
export const simulation_detail_10 = (p:any)=> <div>simulation 10 tick 16ms</div>;
export const simulation_detail_11 = (p:any)=> <div>simulation 11 determinism</div>;
export const simulation_detail_12 = (p:any)=> <div>simulation 12 lockstep</div>;
export const simulation_detail_13 = (p:any)=> <div>simulation 13 fixed point</div>;
export const simulation_detail_14 = (p:any)=> <div>simulation 14 tick 16ms</div>;
export const simulation_detail_15 = (p:any)=> <div>simulation 15 determinism</div>;
export const simulation_detail_16 = (p:any)=> <div>simulation 16 lockstep</div>;
export const simulation_detail_17 = (p:any)=> <div>simulation 17 fixed point</div>;
export const simulation_detail_18 = (p:any)=> <div>simulation 18 tick 16ms</div>;
export const simulation_detail_19 = (p:any)=> <div>simulation 19 determinism</div>;