import React from 'react';
export const pathfindingDetails = () => <div>pathfinding distinct</div>;
export const pathfinding_detail_0 = (p:any)=> <div>pathfinding 0 A*</div>;
export const pathfinding_detail_1 = (p:any)=> <div>pathfinding 1 flow fields</div>;
export const pathfinding_detail_2 = (p:any)=> <div>pathfinding 2 waypoints</div>;
export const pathfinding_detail_3 = (p:any)=> <div>pathfinding 3 obstacles</div>;
export const pathfinding_detail_4 = (p:any)=> <div>pathfinding 4 A*</div>;
export const pathfinding_detail_5 = (p:any)=> <div>pathfinding 5 flow fields</div>;
export const pathfinding_detail_6 = (p:any)=> <div>pathfinding 6 waypoints</div>;
export const pathfinding_detail_7 = (p:any)=> <div>pathfinding 7 obstacles</div>;
export const pathfinding_detail_8 = (p:any)=> <div>pathfinding 8 A*</div>;
export const pathfinding_detail_9 = (p:any)=> <div>pathfinding 9 flow fields</div>;
export const pathfinding_detail_10 = (p:any)=> <div>pathfinding 10 waypoints</div>;
export const pathfinding_detail_11 = (p:any)=> <div>pathfinding 11 obstacles</div>;
export const pathfinding_detail_12 = (p:any)=> <div>pathfinding 12 A*</div>;
export const pathfinding_detail_13 = (p:any)=> <div>pathfinding 13 flow fields</div>;
export const pathfinding_detail_14 = (p:any)=> <div>pathfinding 14 waypoints</div>;
export const pathfinding_detail_15 = (p:any)=> <div>pathfinding 15 obstacles</div>;
export const pathfinding_detail_16 = (p:any)=> <div>pathfinding 16 A*</div>;
export const pathfinding_detail_17 = (p:any)=> <div>pathfinding 17 flow fields</div>;
export const pathfinding_detail_18 = (p:any)=> <div>pathfinding 18 waypoints</div>;
export const pathfinding_detail_19 = (p:any)=> <div>pathfinding 19 obstacles</div>;