import React from 'react';
export const buildingsDetails = () => <div>buildings distinct</div>;
export const buildings_detail_0 = (p:any)=> <div>buildings 0 production</div>;
export const buildings_detail_1 = (p:any)=> <div>buildings 1 tech tree</div>;
export const buildings_detail_2 = (p:any)=> <div>buildings 2 queue</div>;
export const buildings_detail_3 = (p:any)=> <div>buildings 3 cost</div>;
export const buildings_detail_4 = (p:any)=> <div>buildings 4 production</div>;
export const buildings_detail_5 = (p:any)=> <div>buildings 5 tech tree</div>;
export const buildings_detail_6 = (p:any)=> <div>buildings 6 queue</div>;
export const buildings_detail_7 = (p:any)=> <div>buildings 7 cost</div>;
export const buildings_detail_8 = (p:any)=> <div>buildings 8 production</div>;
export const buildings_detail_9 = (p:any)=> <div>buildings 9 tech tree</div>;
export const buildings_detail_10 = (p:any)=> <div>buildings 10 queue</div>;
export const buildings_detail_11 = (p:any)=> <div>buildings 11 cost</div>;
export const buildings_detail_12 = (p:any)=> <div>buildings 12 production</div>;
export const buildings_detail_13 = (p:any)=> <div>buildings 13 tech tree</div>;
export const buildings_detail_14 = (p:any)=> <div>buildings 14 queue</div>;
export const buildings_detail_15 = (p:any)=> <div>buildings 15 cost</div>;
export const buildings_detail_16 = (p:any)=> <div>buildings 16 production</div>;
export const buildings_detail_17 = (p:any)=> <div>buildings 17 tech tree</div>;
export const buildings_detail_18 = (p:any)=> <div>buildings 18 queue</div>;
export const buildings_detail_19 = (p:any)=> <div>buildings 19 cost</div>;